name: Auto build php:fpm-alpine with custom extensions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * 0'
  push:
    branches:
      - 'main'

jobs:
  auto_build_php:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Login
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Generate date tag
        run: echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            whosneo/php:latest
            whosneo/php:${{ env.DATE }}
